### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by hkz01** [aimagelab/camel#13]
Traceback (most recent call last):
  File "evaluation.py", line 121, in <module>
    val_scores, val_samples = evaluate_metrics(model, dataloader_val, text_field)
  File "evaluation.py", line 50, in evaluate_metrics
    scores, _ = evaluation.compute_all_scores(gts, gen)
  File "/home/liu/桌面/xxx文件分享/camel-main1/camel-main/evaluation/__init__.py", line 14, in compute_all_scores
    score, scores = metric.compute_score(gts, gen)
  File "/home/liu/桌面/xxx文件分享/camel-main1/camel-main/evaluation/meteor/meteor.py", line 45, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/home/liu/桌面/xxx文件分享/camel-main1/camel-main/evaluation/meteor/meteor.py", line 62, in _stat
    self.meteor_p.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
环境中我也添加java的jdk了还是没有解决，还要其他什么地方需要注意吗？

**Comment by hkz01** [comment]
可以回答一下吗，我真的解决不掉他
