### ISSUE TITLE
BrokenPipeError:[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by jskbliy** [aimagelab/camel#7]
Traceback (most recent call last):
  File "evaluation.py", line 121, in &lt;module&gt;
    val_scores, val_samples = evaluate_metrics(model, dataloader_val, text_field)
  File "evaluation.py", line 50, in evaluate_metrics
    scores, _ = evaluation.compute_all_scores(gts, gen)
  File "/media/cs/D4FA828F299D817A/camel-main (2)/evaluation/__init__.py", line 14, in compute_all_scores
    score, scores = metric.compute_score(gts, gen)
  File "/media/cs/D4FA828F299D817A/camel-main (2)/evaluation/meteor/meteor.py", line 45, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/media/cs/D4FA828F299D817A/camel-main (2)/evaluation/meteor/meteor.py", line 62, in _stat
    self.meteor_p.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by jskbliy** [comment]
How do I fix this?
