### ISSUE TITLE
Problem when loading pretrained model

### ISSUE THREAD

**Issue by robertodessi** [aimagelab/camel#8]
Hi, thanks a lot for releasing the code for camel.
When I try to load one of the released models and run inference or keep training from a checkpoint I encounter the following error

```
INFO:CaMEL Evaluation
INFO:Namespace(N_dec=3, N_enc=3, annotation_folder='/private/home/rdessi/annotations/', batch_size=25, clip_variant='RN50x16', d_ff=2048, d_model=51
2, disable_mesh=False, head=8, image_folder='/datasets01/COCO/060817/', m=40, network='target', saved_model_path='/private/home/rdessi/EGG/egg/zoo/e
mergent_captioner/finetuning/camel_models/checkpoints/camel_mesh.pth', with_pe=False, workers=0)
Traceback (most recent call last):
  File "evaluation.py", line 111, in <module>
    data = torch.load(fname)
  File "/home/miniconda3/envs/lavis_copy/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/rdessi/miniconda3/envs/lavis_copy/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

I'm using Python 3.8.13 and pytorch 1.10.0+cu102 on linux server.

I tried to load the model from an interactive python shell and get another error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/rdessi/miniconda3/envs/egg/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/private/home/rdessi/miniconda3/envs/egg/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

Any ideas of what could it be?

Thanks in advance!

**Comment by manuelebarraco** [comment]
Hi! We are sorry, some files were corrupted. We re-upload them so now it should work. Thanks!
